import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Articles from "../components/Articles";
import { getAllPost, } from "../lib/api";
import { Post } from "../lib/data";
// import { Post, posts } from "../lib/data";

const Home = ({data}:{data:Post}) => {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center my-20 space-y-16 ">
        <div className="">
          <h1 className="text-blue-500 tracking-wide font-semibold text-5xl">
            Articles
          </h1>
        </div>
        <div className="w-full flex flex-col items-center">
          <Articles posts={data} />
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const data = getAllPost()
  return {
    props: {
      data: data,
    },
  };
};
